name: Our Workflow
on: 
  push:
    # no-main 으로 브렌치를 설정하여 실제 워크플로는 동작하지 않음 (main 으로 변경하면 동작함)
    branches: [ no-main ]
    

#환경설정변수
env:
  REPOSITORY_NAME: hello-web:latest
  USER: /home/kosa
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: gradlew 실행권한 설정 
        run: chmod +x gradlew
        
      - name: test gradlew 
        run: ./gradlew --info test
        
      - name: build gradlew 
        run: ./gradlew bootJar
       
      - name: docker image build 
        run: |
          docker build -t ${{ secrets.USERNAME }}/${{env.REPOSITORY_NAME}} . 
        
      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: docker hub push 
        run: docker push ${{ secrets.USERNAME }}/${{env.REPOSITORY_NAME}}
        
  deploy:
    needs: build
    name: 서버에 배포 단계
    runs-on: [ self-hosted, kosa-host ]
    steps:
    - name: 운영서버에서 docker hub에 로그인 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    
    - name: docker-compose에서 이미지 다운로드 및 실행 
      run: |
        cd ${{env.USER}}/helloWeb/docker
        docker compose down   #docker compose 종료하고 다시 docker hub에서 내려받고 실행한다    
        docker compose pull
        docker compose up -d
        